name: Deploy project to production
on:
  workflow_dispatch:
jobs:
  deploy:
    environment:
      name: production
      url: 'https://carvalho.cv'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to coolify
        run: "curl --request GET '${{ secrets.COOLIFY_PRODUCTION_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'"