name: Deploy project to staging
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    environment:
      name: staging
      url: 'https://st.carvalho.cv'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to coolify
        run: "curl --request GET '${{ secrets.COOLIFY_STAGING_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'"