name: Deploy project to staging
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    environment:
      name: staging
      url: 'https://st.carvalho.cv'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to coolify
        run: "curl --request GET '${{ secrets.COOLIFY_STAGING_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        run: |
          {
            echo 'CHANGELOG<<EOF'
            npx changelogen --from ${{ github.event.before }} --to ${{ github.event.after }}
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Update summary
        run: echo '${{ steps.changelog.outputs.CHANGELOG }}' 1>> $GITHUB_STEP_SUMMARY
      - name: Create annotation
        run: |
          curl \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.POSTHOG_PERSONAL_API_KEY }}" \
          https://eu.posthog.com/api/projects/${{ secrets.POSTHOG_PROJECT_ID }}/annotations/ \
          -d '{
            "content": "[Action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\n\n[Changes](${{ github.server_url }}/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.event.after }})",
            "date_marker":
            "${{ github.event.repository.updated_at}}",
            "scope": "project"
          }'
